const KEY='pc_os_cloud_nobuild_v1';
const uuid=()=>crypto.randomUUID?.()||`PC-${Date.now()}`;
const blank=()=>({id:uuid(),name:'New Flip Project',address:'',city:'',state:'CA',zip:'',bedrooms:3,bathrooms:2,squareFeet:2000,lotSize:0,yearBuilt:0,propertyType:'Single Family',apn:'',purchase:0,arv:0,rehab:0,months:6,interest:11,points:2,sellingPct:5,holdingMonthly:2000,minProfit:75000,status:'Analyzing'});
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{projects:[],current:blank(),view:'projects'};
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(+n||0);
function calc(p){const loan=p.purchase*.85+p.rehab,interest=loan*(p.interest/100)*(p.months/12),points=loan*(p.points/100),holding=p.holdingMonthly*p.months,selling=p.arv*(p.sellingPct/100),total=p.purchase+p.rehab+interest+points+holding+selling,profit=p.arv-total,cash=p.purchase*.15+interest+points+holding,roi=cash?profit/cash*100:0,maxOffer=Math.max(0,p.arv-p.rehab-interest-points-holding-selling-p.minProfit);return{loan,interest,points,holding,selling,total,profit,cash,roi,maxOffer}}
function persist(){const r=calc(state.current);const snap={...state.current,profit:r.profit,roi:r.roi,maxOffer:r.maxOffer};state.projects=[snap,...state.projects.filter(p=>p.id!==snap.id)];localStorage.setItem(KEY,JSON.stringify(state))}
function field(k,label,type='number'){return `<div class="field"><label>${label}</label><input data-key="${k}" type="${type}" value="${String(state.current[k]??'').replaceAll('"','&quot;')}"></div>`}
function render(){const p=state.current,r=calc(p);document.querySelector('#app').innerHTML=`<div class="app"><aside class="sidebar"><div class="brand">Premier Concepts<small>Cloud App — No-Build Edition</small></div><div class="nav"><button data-view="projects" class="${state.view==='projects'?'active':''}">Projects</button><button data-view="deal" class="${state.view==='deal'?'active':''}">Deal Analyzer</button><button data-view="setup" class="${state.view==='setup'?'active':''}">Property Setup</button></div></aside><main class="main"><div class="top"><div><h1>${state.view==='projects'?'Projects Hub':state.view==='deal'?'Deal Analyzer':'Property Setup'}</h1><div style="color:#66758a">Secure RentCast lookup through Netlify Functions.</div></div><div><button class="btn secondary" id="new">+ New Project</button> <button class="btn primary" id="save">Save</button></div></div>${projectsView()}${dealView(r)}${setupView()}</main></div>`;bind()}
function projectsView(){return `<section class="${state.view==='projects'?'':'hidden'}"><div class="project-cards">${state.projects.length?state.projects.map((p,i)=>`<div class="panel project-card"><h3>${p.name}</h3><div>${p.address||'No address'}</div><p><b>Purchase:</b> ${money(p.purchase)}<br><b>ARV:</b> ${money(p.arv)}<br><b>Profit:</b> ${money(p.profit)}<br><b>ROI:</b> ${(+p.roi||0).toFixed(1)}%</p><div class="actions"><button class="btn primary open" data-index="${i}">Open</button><button class="btn danger del" data-index="${i}">Delete</button></div></div>`).join(''):'<div class="panel">No projects yet. Click New Project.</div>'}</div></section>`}
function dealView(r){const decision=r.profit>=state.current.minProfit?'BUY':state.current.purchase>r.maxOffer?'NEGOTIATE':'REVIEW';return `<section class="${state.view==='deal'?'':'hidden'}"><div class="grid">${[['Purchase',state.current.purchase],['ARV',state.current.arv],['Rehab',state.current.rehab],['Profit',r.profit],['ROI',`${r.roi.toFixed(1)}%`],['Maximum Offer',r.maxOffer],['Cash Needed',r.cash],['Decision',decision]].map(([k,v])=>`<div class="card"><span>${k}</span><strong>${typeof v==='number'?money(v):v}</strong></div>`).join('')}</div><div class="panel"><span class="decision ${decision==='BUY'?'buy':decision==='NEGOTIATE'?'negotiate':'walk'}">${decision}</span><table><tbody>${[['Loan',r.loan],['Interest',r.interest],['Points',r.points],['Holding',r.holding],['Selling costs',r.selling],['Total project cost',r.total],['Net profit',r.profit]].map(([k,v])=>`<tr><td>${k}</td><td>${money(v)}</td></tr>`).join('')}</tbody></table></div></section>`}
function setupView(){return `<section class="${state.view==='setup'?'':'hidden'}"><div class="panel"><h3>Property Lookup</h3><div class="address"><input id="address" value="${state.current.address.replaceAll('"','&quot;')}" placeholder="17186 Santa Catherine, Fountain Valley, CA 92708"><button class="btn primary" id="lookup">Get Property Details</button></div><p class="status" id="lookupStatus"></p></div><div class="panel"><div class="form">${field('name','Project Name','text')}${field('city','City','text')}${field('state','State','text')}${field('zip','ZIP','text')}${field('bedrooms','Bedrooms')}${field('bathrooms','Bathrooms')}${field('squareFeet','Square Feet')}${field('lotSize','Lot Size')}${field('yearBuilt','Year Built')}${field('propertyType','Property Type','text')}${field('apn','APN','text')}${field('purchase','Purchase Price')}${field('arv','ARV')}${field('rehab','Rehab Budget')}${field('months','Hold Months')}${field('interest','Interest %')}${field('points','Points %')}${field('sellingPct','Selling Costs %')}${field('holdingMonthly','Monthly Holding')}${field('minProfit','Minimum Profit')}</div></div></section>`}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});document.querySelector('#new').onclick=()=>{persist();state.current=blank();state.view='setup';render()};document.querySelector('#save').onclick=()=>{persist();render()};document.querySelectorAll('[data-key]').forEach(el=>el.onchange=()=>{state.current[el.dataset.key]=el.type==='number'?+el.value:el.value;render()});document.querySelectorAll('.open').forEach(b=>b.onclick=()=>{state.current={...blank(),...state.projects[+b.dataset.index]};state.view='deal';render()});document.querySelectorAll('.del').forEach(b=>b.onclick=()=>{state.projects.splice(+b.dataset.index,1);localStorage.setItem(KEY,JSON.stringify(state));render()});const addr=document.querySelector('#address');if(addr)addr.onchange=()=>state.current.address=addr.value;const lookup=document.querySelector('#lookup');if(lookup)lookup.onclick=lookupProperty}
async function lookupProperty(){const status=document.querySelector('#lookupStatus');state.current.address=document.querySelector('#address').value.trim();if(!state.current.address){status.textContent='Enter the complete address first.';return}status.textContent='Searching property records...';try{const res=await fetch(`/.netlify/functions/property-lookup?address=${encodeURIComponent(state.current.address)}`);const body=await res.json();if(!res.ok)throw new Error(body.error||'Lookup failed');const p=body.property||body;Object.assign(state.current,{address:p.formattedAddress||state.current.address,city:p.city||'',state:p.state||'CA',zip:p.zipCode||'',bedrooms:p.bedrooms??state.current.bedrooms,bathrooms:p.bathrooms??state.current.bathrooms,squareFeet:p.squareFootage??state.current.squareFeet,lotSize:p.lotSize??0,yearBuilt:p.yearBuilt??0,propertyType:p.propertyType||state.current.propertyType,apn:p.apn||''});status.textContent='Property details loaded. Review them, then Save.';setTimeout(render,900)}catch(e){status.textContent=e.message}}
render();
